parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - "@typescript-eslint"
  - import

extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:@typescript-eslint/recommended
  - prettier

globals:
  addEventListener: false
  fetch: false

rules:
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-explicit-any": off
  node/no-missing-import: 'off'
