name: Test

on:
  push:
    branches:
      - '**'
      - '!v**'
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prebuild/linux-armv6:2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set ownership
      run: |
        # Workaround for https://github.com/actions/runner/issues/2033
        chown -R $(id -u):$(id -g) $PWD

    - name: Install DBus
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev cmake

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: "npm"

    #- name: Install dependencies
    #  run: npm ci --ignore-scripts

    - name: Test 1
      run: find . -type f

    #- name: Build
    #  run: npm run pre-build




  test-deploy:
    name: Test Deploy
    permissions:
      contents: write
      packages: write
    needs: [ build, build-cross, build-docker ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: My test
        run: find . -type f
