name: Test

on:
  push:
    branches:
      - '**'
      - '!v**'
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ghcr.io/prebuild/linux-arm64:2
    container:
      image: ${{ matrix.image }}
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set ownership
      run: |
        # Workaround for https://github.com/actions/runner/issues/2033
        chown -R $(id -u):$(id -g) $PWD

    - name: Install DBus
      run: |
        apt-get update
        apt-get install -y libdbus-1-dev cmake

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: "npm"

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Build
      run: npm run pre-build

    - name: My test
      run: find . -type f
