name: Test

on:
  push:
    branches:
      - '**'
      - '!v**'
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ghcr.io/prebuild/linux-arm64:2
    container:
      image: ${{ matrix.image }}
      options: --user root
      env:
        DBus1_ROOT: /usr/lib/aarch64-linux-gnu/cmake
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set ownership
      run: |
        # Workaround for https://github.com/actions/runner/issues/2033
        chown -R $(id -u):$(id -g) $PWD

    - name: Install DBus
      run: |
        echo "deb http://deb.debian.org/debian unstable main" | tee -a /etc/apt/sources.list
        printf "Package: *\nPin: release a=bullseye\nPin-Priority: 700\n\nPackage: *\nPin: release a=unstable\nPin-Priority: 600\n" | tee -a /etc/apt/preferences
        apt-get update
        apt-get -t unstable install -y libdbus-1-3 libdbus-1-dev ninja-build

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: "npm"

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.21.x'

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Build
      run: npm run pre-build

    - name: My test
      run: find . -type f
