name: Test

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install DBus
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libdbus-1-dev:armhf

      - run: ls -1 /usr/arm-linux-gnueabihf/lib/ || echo "Bad"
      - run: ls -1 /usr/lib/arm-linux-gnueabihf/ || echo "Bad"
      - run: ls -1 /usr/include/dbus-1.0 || echo "Bad"
      - run: ls -1 /usr/lib64/dbus-1.0/include || echo Bad
