name: Test

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Test2"
        run: echo $PWD

      - name: "Test3"
        run: ls -1

  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/prebuild/linux-arm64-musl:2
      env:
        NODE_ENV: development
        NO_UPDATE_NOTIFIER: true
      ports:
        - 80
      #volumes:
        #- my_docker_volume:/volume_mount
        #- /input
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test 1
        run: ls -1 -a

